name: build test

on:
  push:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEBUG: 1
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0.38.1
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
